<?php
/**
 * SUMOHeavy_FacebookTracking
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@sumoheavy.com so we can send you a copy immediately.
 *
 * @category   SUMOHeavy
 * @package    SUMOHeavy_FacebookTracking
 * @copyright  Copyright 2013 SUMO Heavy Industries, LLC
 * @license    http://opensource.org/licenses/osl-3.0.php
 * @author     Sean Kennedy <support@sumoheavy.com>
 */

/**
 * Cart
 */
$trackingCode = Mage::getStoreConfig(
    'sumoheavy_facebooktracking/cart/tracking_code'
);
if(Mage::getStoreConfig('sumoheavy_facebooktracking/cart/enabled')
    && $trackingCode):
    ?>
    <script type="text/javascript">
        var fb_param = {};
        fb_param.pixel_id = '<?php echo $trackingCode; ?>';
        (function(){
            var fpw = document.createElement('script');
            fpw.async = true;
            fpw.src = '//connect.facebook.net/en_US/fp.js';
            var ref = document.getElementsByTagName('script')[0];
            ref.parentNode.insertBefore(fpw, ref);
        })();
    </script>
    <noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=<?php echo $trackingCode; ?>&amp;value=0" /></noscript>
<?php
endif; ?>
